iRob_maneuv3r:
    ros__parameters:
        map_frame_id: "map"
        odom_frame_id: "odom"
        robot_frame_id: "base_link"
        use_odom_tf_only: false
        
        walk_kp: 1.0
        walk_ki: 0.0
        walk_kd: 0.0
        walk_max_vel: 0.2
        walk_goal_tolerance: 0.05
        
        rotate_kp: 1.0
        rotate_ki: 0.0
        rotate_kd: 0.0
        rotate_max_vel: 0.1
        rotate_goal_tolerance: 0,174533
        