iRob_maneuv3r:
    ros__parameters:
        map_frame_id: "map"
        odom_frame_id: "odom"
        robot_frame_id: "base_link"
        use_odom_tf_only: true
        
        walk_kp: 0.95
        walk_ki: 0.002
        walk_kd: 0.0
        walk_max_vel: 0.5
        walk_goal_tolerance: 0.05
        
        rotate_kp: 1.2
        rotate_ki: 0.00037
        rotate_kd: 0.0
        rotate_max_vel: 0.7
        rotate_goal_tolerance: 0.01
        